### PR TITLE
Header

### PR DESCRIPTION
**Pull request by bvonpotobsky**
This component has its structure, its style and it's fully responsive. I styled it with scss. The hamburger menu was made with a library.
Links are taken from an array to simulate that they are dynamically displayed. They all have their routes and bring you to the component.

### CODE REVIEW

**Review by MarcosCaballero — APPROVED** [review]
La verdad hermano esta bonito tu código :)

**Review by coltking — APPROVED** [review]
no tiene bootstrap, no me gusta...

**Comment by MarcosCaballero** [comment]
> no tiene bootstrap, no me gusta...

ocupa mucha memoria

**Comment by luciano393** [comment]
I look great friend, keep it up

**Comment by coltking** [comment]
unknown

**Comment by bvonpotobsky** [comment]
Conflicts solved.
Previously the GitHub resolve conflicts button was disabled, it did not allow me to do it.
Now it just allowed me. Conflict solved and branch ready to merge.

**Pull request merged**
